name: Automatically translate README

on:
  push:
    branch:
      - main
  workflow_dispatch:

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests openai GitPython

    - name: Run script
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python tool.py translate